"""旧版交互模块的兼容导入。"""

from .dialogs import (
    choose_directory as _choose_directory,
    choose_linux_directory as _choose_linux_directory,
    choose_linux_mapping_file as _choose_linux_mapping_file,
    choose_mapping_file as _choose_mapping_file,
    choose_terminal_mapping_file as _choose_terminal_mapping_file,
    choose_terminal_directory as _choose_terminal_directory,
    choose_tk_directory as _choose_tk_directory,
    choose_tk_mapping_file as _choose_tk_mapping_file,
    choose_windows_directory as _choose_windows_directory,
    choose_windows_mapping_file as _choose_windows_mapping_file,
    existing_directory as _existing_directory,
    existing_mapping_file as _existing_mapping_file,
)
from .terminal_editor import (
    EditorCommand,
    EditorEvent,
    EditorState,
    ask_curses_workspace_text as _ask_curses_workspace_text,
    ask_valid_text as _ask_valid_text,
    ask_windows_workspace_text as _ask_windows_workspace_text,
    ask_workspace_text as _ask_workspace_text,
)
from .terminal_layout import (
    MENU_LOGO,
    MenuOption,
    fit_terminal_text as _fit_terminal_text,
    menu_frame as _menu_frame,
    move_vertical_cursor as _move_vertical_cursor,
    terminal_text_width as _terminal_text_width,
    truncate_terminal_text as _truncate_terminal_text,
    workspace_choice_frame as _workspace_choice_frame,
    wrapped_input_layout as _wrapped_input_layout,
)
from .terminal_menu import (
    TerminalUnavailable as _DirectorySelectionUnavailable,
    ask as _ask,
    ask_choice as _ask_choice,
    ask_menu_choice as _ask_menu_choice,
    ask_workspace_choice as _ask_workspace_choice,
    choose_curses_menu as _choose_curses_menu,
    choose_windows_menu as _choose_windows_menu,
)

__all__ = [
    "EditorCommand",
    "EditorEvent",
    "EditorState",
    "MENU_LOGO",
    "MenuOption",
    "_DirectorySelectionUnavailable",
    "_ask",
    "_ask_choice",
    "_ask_curses_workspace_text",
    "_ask_menu_choice",
    "_ask_valid_text",
    "_ask_windows_workspace_text",
    "_ask_workspace_choice",
    "_ask_workspace_text",
    "_choose_curses_menu",
    "_choose_directory",
    "_choose_linux_directory",
    "_choose_linux_mapping_file",
    "_choose_mapping_file",
    "_choose_terminal_directory",
    "_choose_terminal_mapping_file",
    "_choose_tk_directory",
    "_choose_tk_mapping_file",
    "_choose_windows_directory",
    "_choose_windows_mapping_file",
    "_choose_windows_menu",
    "_existing_directory",
    "_existing_mapping_file",
    "_fit_terminal_text",
    "_menu_frame",
    "_move_vertical_cursor",
    "_terminal_text_width",
    "_truncate_terminal_text",
    "_workspace_choice_frame",
    "_wrapped_input_layout",
]
